- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "vars/common.yml"
  tasks:
  - name: 1.0 -- Look up ECS Task Definition in {{ aws_env | upper }}
    shell: aws ecs list-task-definitions \
          --family-prefix "{{ aws_project }}-{{ service }}-{{ aws_env }}" \
          --region "{{ aws_region }}"
    register: td_details_cmd_out
  - set_fact:
      td_details: "{{ td_details_cmd_out.stdout | from_json() }}"
  - debug: msg="{{ td_details.taskDefinitionArns[0] }}"
    ignore_errors: yes

  - name: 1.2 -- Artifact Appspec
    template: src=./codedeploy/appspec.j2 dest=./codedeploy/{{ aws_project }}-{{ service }}.yaml
    delegate_to: localhost
  
  - name: 1.3 -- S3 Upload
    shell: aws s3api put-object \
            --bucket "{{ s3_bucket }}" \
            --key ansible/{{ aws_project }}-{{ service }}.yaml \
            --body ./codedeploy/{{ aws_project }}-{{ service }}.yaml
  - name: 1.4 -- Remove Appspec Locally
    file: path=./codedeploy/{{ aws_project }}-{{ service }}.yaml state=absent

  # - name: Create Deployment
  #   shell: aws deploy create-deployment \
  #           --region "us-east-2" \
  #           --application-name devops-poc \
  #           --deployment-group-name devops-poc \
  #           --revision revisionType=S3,s3Location={bucket=devops-poc-bucket,key=ansible/{{ aws_project }}-{{ service }}.yaml,bundleType=YAML}